services:
  app:
    build: ./app
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  ui:
    build: ./ui
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/ui
