version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgresnetwork

networks:
  postgresnetwork:
    driver: bridge

volumes:
  pgdata: 
